name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install dependencies for pre-commit hooks
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Run pre-commit hooks
      - name: Run pre-commit
        run: pre-commit run --all-files

      # Step 5: Check if any files were modified by hooks
      - name: Check for changes after pre-commit
        run: |
          if ! git diff --quiet; then
            echo "Pre-commit hooks modified files. Staging changes..."
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Apply pre-commit fixes"
          fi

      # Step 6: Push changes back to the repository (only for push events)
      - name: Push changes
        if: github.event_name == 'push'
        run: |
          git push
