name: Terraform-Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Cache TFLint plugin directory
      - name: Cache TFLint plugins
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            ubuntu-latest-tflint-

      # Step 3: Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      # Step 4: Display TFLint version
      - name: Show TFLint version
        run: tflint --version

      # Step 5: Initialize TFLint plugins
      - name: Initialize TFLint plugins
        run: tflint --init

      # Step 6: Run TFLint
      - name: Run TFLint
        run: tflint -f compact
